services:
  web:
    container_name: uuca-music
    build: .
    volumes:
      - .:/var/www/html/library
    ports:
      - "8888:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    command: bash -c "npm install && composer install && npx vite build && apache2ctl -D FOREGROUND"
